-- MySQL Script generated by MySQL Workbench
-- Thu Mar 21 21:36:12 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema 360_survey_schema
-- -----------------------------------------------------
-- Schema set  for the implementation of 360 survey tool

-- -----------------------------------------------------
-- Schema 360_survey_schema
--
-- Schema set  for the implementation of 360 survey tool
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `360_survey_schema` ;
USE `360_survey_schema` ;

-- -----------------------------------------------------
-- Table `360_survey_schema`.`Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `360_survey_schema`.`Department` ;

CREATE TABLE IF NOT EXISTS `360_survey_schema`.`Department` (
  `DepartmentID` INT NOT NULL AUTO_INCREMENT,
  `DepartmentName` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`DepartmentID`, `DepartmentName`))
ENGINE = InnoDB
AUTO_INCREMENT = 100;


-- -----------------------------------------------------
-- Table `360_survey_schema`.`Branch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `360_survey_schema`.`Branch` ;

CREATE TABLE IF NOT EXISTS `360_survey_schema`.`Branch` (
  `BranchID` INT NOT NULL AUTO_INCREMENT,
  `BranchName` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`BranchID`, `BranchName`))
ENGINE = InnoDB
AUTO_INCREMENT = 100;


-- -----------------------------------------------------
-- Table `360_survey_schema`.`JobTitle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `360_survey_schema`.`JobTitle` ;

CREATE TABLE IF NOT EXISTS `360_survey_schema`.`JobTitle` (
  `JobTitleID` INT NOT NULL AUTO_INCREMENT,
  `JobTitleName` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`JobTitleID`, `JobTitleName`))
ENGINE = InnoDB
AUTO_INCREMENT = 200;


-- -----------------------------------------------------
-- Table `360_survey_schema`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `360_survey_schema`.`Employee` ;

CREATE TABLE IF NOT EXISTS `360_survey_schema`.`Employee` (
  `EID` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(200) NOT NULL,
  `BranchID` INT NOT NULL,
  `DepartmentID` INT NOT NULL,
  `JobTitleID` INT NOT NULL,
  `PhoneNumber` VARCHAR(20) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`EID`),
  INDEX `fk_BranchID_idx` (`BranchID` ASC),
  INDEX `fk_JobTitle_idx` (`JobTitleID` ASC),
  INDEX `fk_DepartmentID_idx` (`DepartmentID` ASC),
  CONSTRAINT `fk_DepartmentID`
    FOREIGN KEY (`DepartmentID`)
    REFERENCES `360_survey_schema`.`Department` (`DepartmentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BranchID`
    FOREIGN KEY (`BranchID`)
    REFERENCES `360_survey_schema`.`Branch` (`BranchID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_JobTitle`
    FOREIGN KEY (`JobTitleID`)
    REFERENCES `360_survey_schema`.`JobTitle` (`JobTitleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `360_survey_schema`.`Supervisor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `360_survey_schema`.`Supervisor` ;

CREATE TABLE IF NOT EXISTS `360_survey_schema`.`Supervisor` (
  `EID` VARCHAR(45) NOT NULL,
  `SEID` VARCHAR(45) NOT NULL COMMENT 'Provides mapping between the employees and supervisor(s). Note one employee can have multiple supervisors',
  PRIMARY KEY (`EID`, `SEID`),
  INDEX `fk_Supervisor_2_idx` (`SEID` ASC) ,
  CONSTRAINT `fk_Supervisor_1`
    FOREIGN KEY (`EID`)
    REFERENCES `360_survey_schema`.`Employee` (`EID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Supervisor_2`
    FOREIGN KEY (`SEID`)
    REFERENCES `360_survey_schema`.`Employee` (`EID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `360_survey_schema`.`QuestionListTable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `360_survey_schema`.`QuestionListTable` ;

CREATE TABLE IF NOT EXISTS `360_survey_schema`.`QuestionListTable` (
  `QuestionListID` INT NOT NULL AUTO_INCREMENT,
  `Date` DATE NOT NULL,
  `FilePath` VARCHAR(260) NOT NULL,
  PRIMARY KEY (`QuestionListID`))
ENGINE = InnoDB
AUTO_INCREMENT = 100;


-- -----------------------------------------------------
-- Table `360_survey_schema`.`Survey`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `360_survey_schema`.`Survey` ;

CREATE TABLE IF NOT EXISTS `360_survey_schema`.`Survey` (
  `SurveyID` INT NOT NULL AUTO_INCREMENT,
  `Date` DATE NOT NULL,
  `QuestionaireID` INT NOT NULL,
  `State` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`SurveyID`),
  INDEX `fk_Survey_1_idx` (`QuestionaireID` ASC) ,
  CONSTRAINT `fk_Survey_1`
    FOREIGN KEY (`QuestionaireID`)
    REFERENCES `360_survey_schema`.`QuestionListTable` (`QuestionListID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 100;


-- -----------------------------------------------------
-- Table `360_survey_schema`.`QuestionCategoryTable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `360_survey_schema`.`QuestionCategoryTable` ;

CREATE TABLE IF NOT EXISTS `360_survey_schema`.`QuestionCategoryTable` (
  `QuestionListID` INT NOT NULL,
  `CategoryID` SMALLINT(1) NOT NULL,
  `CategoryName` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`QuestionListID`, `CategoryID`),
  CONSTRAINT `fk_QuestionListID`
    FOREIGN KEY (`QuestionListID`)
    REFERENCES `360_survey_schema`.`QuestionListTable` (`QuestionListID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `360_survey_schema`.`QuestionsTable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `360_survey_schema`.`QuestionsTable` ;

CREATE TABLE IF NOT EXISTS `360_survey_schema`.`QuestionsTable` (
  `QuestionListID` INT NOT NULL,
  `CategoryID` SMALLINT(1) NOT NULL,
  `QuestionNumber` SMALLINT(1) NOT NULL,
  `Question` VARCHAR(255) NOT NULL,
  `Type` TINYINT(1) UNSIGNED NULL DEFAULT 0,
  PRIMARY KEY (`QuestionListID`, `CategoryID`, `QuestionNumber`),
  CONSTRAINT `fk_QuestionCategory`
    FOREIGN KEY (`QuestionListID` , `CategoryID`)
    REFERENCES `360_survey_schema`.`QuestionCategoryTable` (`QuestionListID` , `CategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `360_survey_schema`.`SurveyFeedback`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `360_survey_schema`.`SurveyFeedback` ;

CREATE TABLE IF NOT EXISTS `360_survey_schema`.`SurveyFeedback` (
  `SurveyID` INT NOT NULL,
  `EID` VARCHAR(45) NOT NULL,
  `SurveyorEID` VARCHAR(255) NOT NULL,
  `SurveyorType` TINYINT(1) NOT NULL,
  `QuestionCategoryID` SMALLINT(1) NOT NULL,
  `QuestionID` SMALLINT(1) NOT NULL,
  `Rating` SMALLINT(1) NOT NULL,
  PRIMARY KEY (`SurveyID`, `EID`, `SurveyorEID`, `QuestionCategoryID`, `QuestionID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `360_survey_schema`.`SurveyAssignment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `360_survey_schema`.`SurveyAssignment` ;

CREATE TABLE IF NOT EXISTS `360_survey_schema`.`SurveyAssignment` (
  `SurveyID` INT NOT NULL,
  `AssignorEID` VARCHAR(45) NULL,
  `EID` VARCHAR(45) NOT NULL,
  `SurveyorEID` VARCHAR(255) NOT NULL,
  `SurveyorType` TINYINT(1) NOT NULL,
  `AssignedDate` DATE NOT NULL,
  `ResponseDate` DATE NULL,
  PRIMARY KEY (`SurveyID`, `EID`, `SurveyorEID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `360_survey_schema`.`Login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `360_survey_schema`.`Login` ;

CREATE TABLE IF NOT EXISTS `360_survey_schema`.`Login` (
  `UserName` VARCHAR(90) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`UserName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `360_survey_schema`.`Peers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `360_survey_schema`.`Peers` ;

CREATE TABLE IF NOT EXISTS `360_survey_schema`.`Peers` (
  `EID` VARCHAR(45) NOT NULL,
  `PeerID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`EID`, `PeerID`),
  INDEX `fk_Peers_1PID_idx` (`PeerID` ASC) ,
  CONSTRAINT `fk_Peers_1EID`
    FOREIGN KEY (`EID`)
    REFERENCES `360_survey_schema`.`Employee` (`EID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Peers_1PID`
    FOREIGN KEY (`PeerID`)
    REFERENCES `360_survey_schema`.`Employee` (`EID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `360_survey_schema`.`DirectReports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `360_survey_schema`.`DirectReports` ;

CREATE TABLE IF NOT EXISTS `360_survey_schema`.`DirectReports` (
  `EID` VARCHAR(45) NOT NULL,
  `DirectReportEID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`EID`, `DirectReportEID`),
  INDEX `fk_DirectReports_2_idx` (`DirectReportEID` ASC) ,
  CONSTRAINT `fk_DirectReports_1`
    FOREIGN KEY (`EID`)
    REFERENCES `360_survey_schema`.`Employee` (`EID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DirectReports_2`
    FOREIGN KEY (`DirectReportEID`)
    REFERENCES `360_survey_schema`.`Employee` (`EID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `360_survey_schema`.`ExternalSurveyor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `360_survey_schema`.`ExternalSurveyor` ;

CREATE TABLE IF NOT EXISTS `360_survey_schema`.`ExternalSurveyor` (
  `ExternalSurveyorId` INT NOT NULL AUTO_INCREMENT,
  `EID` VARCHAR(255) NOT NULL,
  `Name` VARCHAR(200) NOT NULL,
  `CompanyName` VARCHAR(120) NULL,
  `Department` VARCHAR(120) NULL,
  `JobTitleName` VARCHAR(200) NULL,
  PRIMARY KEY (`ExternalSurveyorId`, `EID`))
ENGINE = InnoDB
AUTO_INCREMENT = 100;


-- -----------------------------------------------------
-- Table `360_survey_schema`.`SurveyFeedbackText`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `360_survey_schema`.`SurveyFeedbackText` ;

CREATE TABLE IF NOT EXISTS `360_survey_schema`.`SurveyFeedbackText` (
  `SurveyID` INT NOT NULL,
  `EID` VARCHAR(45) NOT NULL,
  `SurveyorEID` VARCHAR(255) NOT NULL,
  `SurveyorType` TINYINT(1) NULL,
  `QuestionCategoryID` SMALLINT(1) NOT NULL,
  `QuestionID` SMALLINT(1) NOT NULL,
  `Text` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`SurveyID`, `EID`, `SurveyorEID`, `QuestionCategoryID`, `QuestionID`))
ENGINE = InnoDB
COMMENT = 'Support for free text input in survey';

USE `360_survey_schema` ;

-- -----------------------------------------------------
-- Placeholder table for view `360_survey_schema`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `360_survey_schema`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `360_survey_schema`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `360_survey_schema`.`view1`;
DROP VIEW IF EXISTS `360_survey_schema`.`view1` ;
USE `360_survey_schema`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
